### ISSUE TITLE
Missing objects

### ISSUE THREAD

**Issue by jrb0030** [Neoky/Lua_Roguelite#2]
I have noticed a few times that an item or enemy in a scene's object list will not appear in the scene.  For example, when I arrived in scene14 the boss was not visible in the room.  This is a sporadic issue so I cannot determine what is the cause.

**Comment by smm0034** [comment]
This is probably because the scene names were not being set correctly so most objects were being written to scene 3's lists. I noticed that you just recently fixed that so please let me know if you see this issue again after the update and I will take a more in-depth look.

**Comment by smm0034** [comment]
Just pushed a fix to scene transitions where scenes where getting overwritten in the scene list when a new scene was being inserted. This may have fixed the problem as well.
